import { MCP_GUIDE_BODY } from "./mcpGuide/body.js";

export function buildMcpGuide(opts: {
  sessionId?: string;
  agentId?: string;
  runtimeId?: string;
  userParticipantId: string;
  existingSession?: boolean;
}): string {
  const { sessionId, agentId, runtimeId } = opts;
  const identityLine =
    agentId !== undefined
      ? `\n- **Your participant id:** \`${agentId}\` — your default \`participant_id\`; omit it on tool calls unless acting as someone else.`
      : "";
  const sessionLine =
    sessionId !== undefined
      ? `\n- **Your F-Mark session id:** \`${sessionId}\` — your default \`session_id\`; omit it on tool calls unless writing to another session.`
      : "\n- **No F-Mark session id was pinned.** Ask the user which session to join before writing.";
  const runtimeLine = mcpRuntimeLine(runtimeId);
  const firstAction = mcpFirstAction(opts.existingSession);

  return `# F-Mark agent onboarding
*Auto-generated by the running kernel. This is the MCP-first guide for managed agents.*

## Connection

${runtimeLine}${identityLine}${sessionLine}

## First Action

${firstAction}

${MCP_GUIDE_BODY}
`;
}

function mcpRuntimeLine(runtimeId: string | undefined): string {
  if (runtimeId === "claude") {
    return "Claude exposes these as MCP tools from the `fmark` server, usually named like `mcp__fmark__fmark_post_prose` in allow lists.";
  }
  if (runtimeId === "codex") {
    return "Codex exposes these as MCP tools from the `fmark` server. Prefer the MCP tools over shell commands.";
  }
  return "Use the F-Mark MCP tools from the `fmark` server.";
}

function mcpFirstAction(existingSession: boolean | undefined): string {
  const opening = [
    'Open your turn deliberately. Do **not** post "Connected." or any other filler acknowledgement — the launch/wake packet already proves you are online.',
    "Internal identifiers — your participant id, session id, runtime id — are plumbing. Never state them in prose; the user has no use for them.",
    "",
  ];
  if (existingSession) {
    return [
      ...opening,
      "1. Read the Existing Session Brief above and the current context before writing.",
      '2. If the wake packet lists events with `mode: "comment"`, fetch and answer those first.',
      "3. If the latest user message is an active request, answer or continue it directly.",
    ].join("\n");
  }
  return [
    ...opening,
    "1. If the name is still `new-session` **and** a user request exists, call `fmark_rename_session` with a kebab-case slug derived from that request — **before** posting any output. No request yet? Leave the placeholder; never invent a name.",
    '2. If the wake packet lists events with `mode: "comment"`, fetch and answer those first.',
    "3. If the user asked for something, begin that work directly.",
    "4. If there is no request yet, post one short, friendly ready line (a plain hello) and end your turn. Do not recap your onboarding steps, mention renaming, or ask what to work on — just be ready.",
  ].join("\n");
}
