import { renderHooksSection } from "./hooksSection.js";

export function buildRestGuide(opts: {
  baseUrl: string;
  agentMd: string;
  sessionId?: string;
  agentId?: string;
  runtimeId?: string;
  userParticipantId: string;
}): string {
  const { baseUrl, agentMd, sessionId, agentId, runtimeId, userParticipantId } = opts;
  const agentPlaceholder = agentId ?? "<your-agent-id>";
  const identityLine =
    agentId !== undefined
      ? `\n- **Your participant id:** \`${agentId}\` (already registered — skip the \`POST /participants/register\` step).`
      : "";
  const sessionSection = restSessionSection(baseUrl, sessionId, agentPlaceholder);

  return `# F-Mark agent onboarding
*Auto-generated by the running kernel at \`${baseUrl}\`. Treat this page as the authoritative live config; \`.f-mark/AGENT.md\` is a static fallback.*

## Connection

- **Base URL:** \`${baseUrl}\`
- **Bearer token:** read from \`.f-mark/.token\` in the project root. Send as \`Authorization: Bearer <token>\` on every request (the \`/health\` endpoint is the only exception).
- **WebSocket (optional):** \`${baseUrl.replace(/^http/, "ws")}/ws\` — broadcasts new event filenames in real-time.${identityLine}

## Verify your tooling

Before you send anything, check that you have the F-Mark skill installed locally so you understand the protocol fully.

### Skill (REQUIRED)
1. Check for \`.claude/skills/f-mark/SKILL.md\` in the current project.
2. If absent, copy the bundled skill from \`node_modules/f-mark/assets/claude-skill/f-mark/\` into \`.claude/skills/f-mark/\`:
   \`\`\`bash
   mkdir -p .claude/skills/f-mark
   cp -r node_modules/f-mark/assets/claude-skill/f-mark/* .claude/skills/f-mark/
   \`\`\`
3. After copying, read \`.claude/skills/f-mark/SKILL.md\` and \`.claude/skills/f-mark/api.md\` for the full reference.

${renderHooksSection(runtimeId, agentId, userParticipantId)}
${sessionSection}

## Never draw ASCII art

**Never** render visual or structural output as characters in prose — no
ASCII art, box-drawing, or "diagram in a code block". Use a real surface:
diagrams/flowcharts/pipelines/state machines → \`flow\` events; rendered
UI, mockups, and rich visuals → \`html\` events. The posting surface is
not the design target: before generating \`html\` (or \`alternatives\`),
state which of three visual targets applies. **target-repo-ui** — UI for a
specific repo or product (the current project or another) → read that
repo's own styles first and match them, not F-Mark's applied theme.
**fmark-ui** — UI that ships in F-Mark itself → read the real renderer
source under \`packages/renderer/src\` and reuse its class names, resolving
colors via \`GET /theme\`. **session-artifact** — an unbound chart,
analysis, or standalone visual → default to the Amber house theme
(\`GET /theme?theme=amber\`). Markdown prose, tables, and lists are fine
for ordinary text.

## Documents vs conversation

Two surfaces — choose deliberately. The **document** is named, composed,
and durable: put substantial structured work (plans, specs, designs,
analyses) there. The **conversation** is messages and turns: use it for
back-and-forth. A casual message is a prose POST with no \`name\` and no
\`append_to\`.

## Composing long documents

For documents that mix prose, flow charts, and other embeds, **use
\`append_to\`** to build a single composable doc out of multiple events:

1. POST a named prose (the **anchor**). Keep new anchors **header-only**
   — leave \`content\` empty. The anchor's \`name\` is the document title.
2. Append every part with \`append_to: <anchor filename>\` on each
   subsequent POST. Pick the part's kind to match its role: prose for
   sections, flow for diagrams, file for images, html for widgets,
   choices/todo/tool-use for interactive panels.
3. The renderer collapses the anchor + all blocks into a single visible
   document, in event-arrival order.

### Common pitfalls

- **One anchor per deliverable.** \`append_to\` extends only the document
  you are *currently* building. A new deliverable opens a new anchor —
  never append onto a prior, finished document, or whatever anchor was
  open from an earlier turn.
- Anchors are header-only. New anchors with markdown content still render
  (legacy fallback), but new authoring should keep content empty.
- Use prose \`mode: "comment"\` for comments; **never** put \`name\` on a
  comment.
- \`lines\` is comment-only and only applies to prose-text targets.
- When superseding a block, **preserve its \`append_to\`** so the slot is
  kept; otherwise the supersedor renders as a new top-level event.
- Mark removed blocks with prose \`removed: true\` (and \`supersedes:\`
  the block's filename), not empty content. A prose tombstone may
  supersede any block kind.

See \`${baseUrl}/best-practices\` for a worked four-event canonical
example, full JSON payloads, and the complete error-rule table.

## Full protocol (from \`.f-mark/AGENT.md\`)

${agentMd.trimStart()}
`;
}

function restSessionSection(
  baseUrl: string,
  sessionId: string | undefined,
  agentPlaceholder: string,
): string {
  if (sessionId === undefined) {
    return `\n## No session selected\n\nThe user did not pin a session for you. List existing ones with \`GET ${baseUrl}/sessions\` and ask which to join, or create a new one with \`POST ${baseUrl}/sessions\` (body: \`{"slug":"…"}\`).\n`;
  }

  return `\n## Your session\n\n- **Session id:** \`${sessionId}\`\n- **Read events:** \`GET ${baseUrl}/sessions/${sessionId}/events?since=<last_seen_ts>\`\n\n### First action — say hello\n\nAfter you register as a participant, immediately POST a short prose message so the user sees you are online. Replace \`${agentPlaceholder}\` with the id returned from \`POST /participants/register\`:\n\n\`\`\`bash\ncurl -X POST '${baseUrl}/sessions/${sessionId}/events/prose' \\\n  -H "Authorization: Bearer $(cat .f-mark/.token)" \\\n  -H 'Content-Type: application/json' \\\n  -d '{"participant_id":"${agentPlaceholder}","content":"Connected. What would you like to work on?"}'\n\`\`\`\n\nThen wait for the user's next prose, read it via the \`GET /events\` endpoint above, and respond with another prose (or a \`choices\`, \`turn-end\`, etc.). End every turn with \`POST /sessions/${sessionId}/events/turn-end\`.\n`;
}
