import { readFile } from "node:fs/promises";
import type { FastifyInstance } from "fastify";
import type { Paths } from "../paths.js";
import { sessionExists } from "../sessions.js";
import { listParticipants } from "../participants.js";
import { normaliseDeps, resolvePaths, type PathDeps } from "./pathDeps.js";
import { renderClaudeInstallSnippet } from "../hooksInstall/claude.js";
import { renderCodexInstallSnippet } from "../hooksInstall/codex.js";
import { renderOpencodeInstallSnippet } from "../hooksInstall/opencode.js";

interface GuideQuery {
  session_id?: string;
  /** Backward-compat alias for `session_id`. */
  sessionId?: string;
  agent_id?: string;
  runtime_id?: string;
}

function renderHooksSection(
  runtimeId: string | undefined,
  agentId: string | undefined,
  userParticipantId: string,
): string {
  const userPlaceholder = userParticipantId;
  const agentPlaceholder = agentId ?? "<your-agent-id>";
  if (runtimeId === "claude") {
    return [
      "### Hooks (Claude Code)",
      "",
      renderClaudeInstallSnippet(),
    ].join("\n");
  }
  if (runtimeId === "codex") {
    return [
      "### Hooks (Codex)",
      "",
      renderCodexInstallSnippet(agentPlaceholder, userPlaceholder),
    ].join("\n");
  }
  if (runtimeId === "opencode") {
    return [
      "### Hooks (Opencode)",
      "",
      renderOpencodeInstallSnippet(),
    ].join("\n");
  }
  return [
    "### Hooks",
    "",
    "F-Mark v0.4 supports these runtimes:",
    "- **Claude Code** — hooks installed in `~/.claude/settings.json`",
    "- **Codex** — hooks enabled in `~/.codex/config.toml` and installed in `~/.codex/hooks.json`",
    "- **Opencode** — an in-process plugin installed at `.opencode/plugin/fmark.ts` posts events to the kernel",
    "",
    "Pass `?runtime_id=claude|codex|opencode` to this endpoint for the install snippet.",
  ].join("\n");
}

export function buildMcpGuide(opts: {
  sessionId?: string;
  agentId?: string;
  runtimeId?: string;
  userParticipantId: string;
}): string {
  const { sessionId, agentId, runtimeId } = opts;
  const agentPlaceholder = agentId ?? "<your-agent-id>";
  const identityLine =
    agentId !== undefined
      ? `\n- **Your participant id:** \`${agentId}\`. Use it when a F-Mark MCP tool asks for \`participant_id\`.`
      : "";
  const sessionLine =
    sessionId !== undefined
      ? `\n- **Your F-Mark session id:** \`${sessionId}\`. Use it when a F-Mark MCP tool asks for \`session_id\`.`
      : "\n- **No F-Mark session id was pinned.** Ask the user which session to join before writing.";

  const runtimeLine =
    runtimeId === "claude"
      ? "Claude exposes these as MCP tools from the `fmark` server, usually named like `mcp__fmark__fmark_post_prose` in allow lists."
      : runtimeId === "codex"
        ? "Codex exposes these as MCP tools from the `fmark` server. Prefer the MCP tools over shell commands."
        : "Use the F-Mark MCP tools from the `fmark` server.";

  return `# F-Mark agent onboarding
*Auto-generated by the running kernel. This is the MCP-first guide for managed agents.*

## Connection

${runtimeLine}${identityLine}${sessionLine}

## First Action

Immediately call \`fmark_post_prose\` so the user sees you are online.

Use these arguments:

\`\`\`json
{
  "participant_id": "${agentPlaceholder}",
  "session_id": "${sessionId ?? "<session-id>"}",
  "content": "Connected. What would you like to work on?"
}
\`\`\`

After your visible response for a turn, call \`fmark_end_turn\` with the same \`participant_id\` and \`session_id\`.

## Reading Context

- When F-Mark wakes you with a wake packet, call \`fmark_get_inbox\` first. It returns unread activity for your participant and marks those returned items seen.
- Use \`fmark_read_events\` to read the current session.
- Use the \`fmark://guide\` resource when you need this guide again.
- Do not use shell commands to write F-Mark events when MCP tools are available.

### Responding to Comments

A user comment is a \`prose\` event with \`mode: "comment"\`, an \`append_to\` filename pointing at the parent prose, and optional \`lines\` (\`[start, end]\`, 1-indexed inclusive) identifying the slice being commented on. The wake packet surfaces these fields directly on the event (\`append_to\`, \`mode\`, \`lines\`) so you can recognise comments before fetching the inbox.

When the inbox contains a comment:
1. Locate the parent event with \`fmark_read_events\` and find the record whose \`filename\` matches the comment's \`append_to\`. The parent's \`payload.content\` is the body; the comment's \`lines\` are 1-indexed into that content. (\`fmark_read_event\` works too, but it returns the raw \`.prose.md\` markdown including frontmatter — you'd need to strip the frontmatter before counting lines.)
2. Treat the comment's \`content\` as a question about *that specific slice* — not a standalone message. Your reply should reference the anchored text or amend it.
3. Reply with \`fmark_post_prose\` using \`mode: "comment"\`, the same \`append_to\`, the same \`lines\` (when the original comment had them), and \`in_reply_to: <comment filename>\` to thread the response onto the original comment.

## Core MCP Tools

| Tool | Use |
|---|---|
| \`fmark_get_inbox\` | Read unread session activity for you after a wake packet. |
| \`fmark_read_events\` | Read the session event feed. |
| \`fmark_post_prose\` | Write prose, comments, replies, revisions, anchors, and removals. |
| \`fmark_post_alternatives\` | Present multiple HTML mockups as one visual multi-option widget to compare and pick from. |
| \`fmark_end_turn\` | Mark your turn complete. |

## Composing Long Documents

For documents that mix prose, diagrams, files, and rich embeds, use \`append_to\` to build a single composable document out of multiple events:

1. Call \`fmark_post_prose\` to create a named prose anchor. Keep new anchors header-only by setting \`content\` to an empty string and \`name\` to the document title.
2. Append prose sections with \`fmark_post_prose\` and \`append_to: <anchor filename>\`.
3. Use prose \`mode: "comment"\` for comments. Do not put \`name\` on comments.
4. When superseding a block, preserve its \`append_to\` so the renderer keeps the same document slot.
5. Mark removed prose blocks with \`removed: true\` and \`supersedes: <old filename>\`.

## Visual Alternatives

When you generate several HTML mockups/designs and want the user to compare and choose, use \`fmark_post_alternatives\` instead of posting separate \`fmark_post_html\` embeds:

1. One call carries \`{ id, question, multi, options: [{ id, label, html, css?, js?, title? }] }\`. Each option's \`html\` renders as a live preview in a selectable grid, each with a fullscreen view button.
2. Record the pick with \`fmark_post_choice\` (\`choices_id\` = your \`id\`, \`selected\` = chosen option ids). The user usually does this from the UI.
3. To embed the widget in a document, set \`append_to\` on the alternatives call — never on the child HTML. Preserve \`append_to\` when superseding the widget, like any other block.
4. Do not hand-write an option's \`html\` ref on \`fmark_post_choices\`; that field is only for an existing html bundle filename F-Mark already returned.

If a needed non-prose MCP tool is not available in this runtime, ask the user before falling back to another integration path.

## REST Reference

The raw HTTP protocol reference is intentionally not included in this managed-agent guide. Use \`/guide-rest-variant\` only for debugging or custom non-MCP integrations.
`;
}

function buildRestGuide(opts: {
  baseUrl: string;
  agentMd: string;
  sessionId?: string;
  agentId?: string;
  runtimeId?: string;
  userParticipantId: string;
}): string {
  const { baseUrl, agentMd, sessionId, agentId, runtimeId, userParticipantId } = opts;
  const agentPlaceholder = agentId ?? "<your-agent-id>";
  const identityLine =
    agentId !== undefined
      ? `\n- **Your participant id:** \`${agentId}\` (already registered — skip the \`POST /participants/register\` step).`
      : "";
  const sessionSection =
    sessionId === undefined
      ? `\n## No session selected\n\nThe user did not pin a session for you. List existing ones with \`GET ${baseUrl}/sessions\` and ask which to join, or create a new one with \`POST ${baseUrl}/sessions\` (body: \`{"slug":"…"}\`).\n`
      : `\n## Your session\n\n- **Session id:** \`${sessionId}\`\n- **Read events:** \`GET ${baseUrl}/sessions/${sessionId}/events?since=<last_seen_ts>\`\n\n### First action — say hello\n\nAfter you register as a participant, immediately POST a short prose message so the user sees you are online. Replace \`${agentPlaceholder}\` with the id returned from \`POST /participants/register\`:\n\n\`\`\`bash\ncurl -X POST '${baseUrl}/sessions/${sessionId}/events/prose' \\\n  -H "Authorization: Bearer $(cat .f-mark/.token)" \\\n  -H 'Content-Type: application/json' \\\n  -d '{"participant_id":"${agentPlaceholder}","content":"Connected. What would you like to work on?"}'\n\`\`\`\n\nThen wait for the user's next prose, read it via the \`GET /events\` endpoint above, and respond with another prose (or a \`choices\`, \`turn-end\`, etc.). End every turn with \`POST /sessions/${sessionId}/events/turn-end\`.\n`;

  return `# F-Mark agent onboarding
*Auto-generated by the running kernel at \`${baseUrl}\`. Treat this page as the authoritative live config; \`.f-mark/AGENT.md\` is a static fallback.*

## Connection

- **Base URL:** \`${baseUrl}\`
- **Bearer token:** read from \`.f-mark/.token\` in the project root. Send as \`Authorization: Bearer <token>\` on every request (the \`/health\` endpoint is the only exception).
- **WebSocket (optional):** \`${baseUrl.replace(/^http/, "ws")}/ws\` — broadcasts new event filenames in real-time.${identityLine}

## Verify your tooling

Before you send anything, check that you have the F-Mark skill installed locally so you understand the protocol fully.

### Skill (REQUIRED)
1. Check for \`.claude/skills/f-mark/SKILL.md\` in the current project.
2. If absent, copy the bundled skill from \`node_modules/f-mark/assets/claude-skill/f-mark/\` into \`.claude/skills/f-mark/\`:
   \`\`\`bash
   mkdir -p .claude/skills/f-mark
   cp -r node_modules/f-mark/assets/claude-skill/f-mark/* .claude/skills/f-mark/
   \`\`\`
3. After copying, read \`.claude/skills/f-mark/SKILL.md\` and \`.claude/skills/f-mark/api.md\` for the full reference.

${renderHooksSection(runtimeId, agentId, userParticipantId)}
${sessionSection}
---

## Composing long documents

For documents that mix prose, flow charts, and other embeds, **use
\`append_to\`** to build a single composable doc out of multiple events:

1. POST a named prose (the **anchor**). Keep new anchors **header-only**
   — leave \`content\` empty. The anchor's \`name\` is the document title.
2. Append every part with \`append_to: <anchor filename>\` on each
   subsequent POST. Pick the part's kind to match its role: prose for
   sections, flow for diagrams, file for images, html for widgets,
   choices/todo/tool-use for interactive panels.
3. The renderer collapses the anchor + all blocks into a single visible
   document, in event-arrival order.

### Common pitfalls

- Anchors are header-only. New anchors with markdown content still render
  (legacy fallback), but new authoring should keep content empty.
- Use prose \`mode: "comment"\` for comments; **never** put \`name\` on a
  comment.
- \`lines\` is comment-only and only applies to prose-text targets.
- When superseding a block, **preserve its \`append_to\`** so the slot is
  kept; otherwise the supersedor renders as a new top-level event.
- Mark removed blocks with prose \`removed: true\` (and \`supersedes:\`
  the block's filename), not empty content. A prose tombstone may
  supersede any block kind.

See \`${baseUrl}/best-practices\` for a worked four-event canonical
example, full JSON payloads, and the complete error-rule table.

---

## Full protocol (from \`.f-mark/AGENT.md\`)

${agentMd.trimStart()}
`;
}

export function registerGuideRoute(
  app: FastifyInstance,
  pOrDeps: Paths | PathDeps,
): void {
  const deps = normaliseDeps(pOrDeps);

  async function guideData(req: { query: GuideQuery; headers: Record<string, unknown> }, reply: { code(code: number): { send(body: unknown): void } }): Promise<{
    p: Paths;
    baseUrl: string;
    agentMd?: string;
    sessionId?: string;
    agentId?: string;
    runtimeId?: string;
    userParticipantId: string;
  } | null> {
    const p = resolvePaths(deps);
    const sessionId = req.query.session_id ?? req.query.sessionId;
    const agentId = req.query.agent_id;
    const runtimeId = req.query.runtime_id;
    if (sessionId !== undefined && !(await sessionExists(p, sessionId))) {
      reply.code(404).send({ error: `session not found: ${sessionId}` });
      return null;
    }
    const host = (req.headers.host as string | undefined) ?? `localhost:7777`;
    const xfProto = req.headers["x-forwarded-proto"];
    const proto =
      typeof xfProto === "string" && xfProto.length > 0 ? xfProto : "http";
    const baseUrl = `${proto}://${host}`;
    // Find the first registered user participant to substitute into the
    // UserPromptSubmit hook snippets. If none exists (e.g. an agent-only
    // project), fall back to the legacy `us-yourname` placeholder.
    let userParticipantId = "us-yourname";
    try {
      const parts = await listParticipants(p);
      for (const [id, part] of Object.entries(parts)) {
        if (part.kind === "user") {
          userParticipantId = id;
          break;
        }
      }
    } catch {
      // leave the fallback
    }
    return {
      p,
      baseUrl,
      sessionId,
      agentId,
      runtimeId,
      userParticipantId,
    };
  }

  app.get<{ Querystring: GuideQuery }>("/guide", async (req, reply) => {
    const data = await guideData(req, reply);
    if (data === null) return;
    reply.type("text/markdown; charset=utf-8");
    return buildMcpGuide({
      sessionId: data.sessionId,
      agentId: data.agentId,
      runtimeId: data.runtimeId,
      userParticipantId: data.userParticipantId,
    });
  });

  app.get<{ Querystring: GuideQuery }>("/guide-rest-variant", async (req, reply) => {
    const data = await guideData(req, reply);
    if (data === null) return;
    let agentMd = "";
    try {
      agentMd = await readFile(data.p.agentMd(), "utf8");
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
    }
    reply.type("text/markdown; charset=utf-8");
    return buildRestGuide({
      baseUrl: data.baseUrl,
      agentMd,
      sessionId: data.sessionId,
      agentId: data.agentId,
      runtimeId: data.runtimeId,
      userParticipantId: data.userParticipantId,
    });
  });
}
