import { readFile } from "node:fs/promises";
import type { FastifyInstance } from "fastify";
import type { Paths } from "../paths.js";
import { sessionExists } from "../sessions.js";
import { listParticipants } from "../participants.js";
import { normaliseDeps, resolvePaths, type PathDeps } from "./pathDeps.js";

interface GuideQuery {
  session_id?: string;
  /** Backward-compat alias for `session_id`. */
  sessionId?: string;
  agent_id?: string;
  runtime_id?: string;
}

function renderHooksSection(
  runtimeId: string | undefined,
  agentId: string | undefined,
  userParticipantId: string,
): string {
  const userPlaceholder = userParticipantId;
  const agentPlaceholder = agentId ?? "<your-agent-id>";
  if (runtimeId === "claude") {
    return [
      "### Hooks (Claude Code)",
      "",
      "Add the auto-stream hook to `~/.claude/settings.json`:",
      "",
      "```json",
      '"hooks": {',
      '  "Stop": [{ "hooks": [{ "type": "command", "command": "npx -y f-mark hook auto-stream ' +
        agentPlaceholder +
        '" }] }],',
      '  "UserPromptSubmit": [{ "hooks": [{ "type": "command", "command": "npx -y f-mark hook auto-stream ' +
        userPlaceholder +
        ' --kind user" }] }]',
      "}",
      "```",
    ].join("\n");
  }
  if (runtimeId === "codex") {
    return [
      "### Hooks (Codex)",
      "",
      "Add to `~/.codex/config.toml`:",
      "",
      "```toml",
      "[[hooks.Stop]]",
      'command = ["npx", "-y", "f-mark", "hook", "auto-stream", "' +
        agentPlaceholder +
        '"]',
      "timeout = 30",
      "",
      "[[hooks.UserPromptSubmit]]",
      'command = ["npx", "-y", "f-mark", "hook", "auto-stream", "' +
        userPlaceholder +
        '", "--kind", "user"]',
      "timeout = 10",
      "```",
      "",
      "On first run, Codex will prompt you to trust the hook command. Approve once.",
    ].join("\n");
  }
  if (runtimeId === "gemini") {
    return [
      "### Hooks (Gemini CLI)",
      "",
      "Gemini CLI uses **manual-stream mode** in F-Mark v0.4. The model itself POSTs prose, tool-use, and turn-end events — no hooks needed.",
    ].join("\n");
  }
  return [
    "### Hooks",
    "",
    "F-Mark v0.4 supports three runtimes:",
    "- **Claude Code** — hooks installed in `~/.claude/settings.json`",
    "- **Codex** — hooks installed in `~/.codex/config.toml`",
    "- **Gemini CLI** — manual-stream mode (no hooks needed)",
    "",
    "Pass `?runtime_id=claude|codex|gemini` to this endpoint for the install snippet.",
  ].join("\n");
}

function buildGuide(opts: {
  baseUrl: string;
  agentMd: string;
  sessionId?: string;
  agentId?: string;
  runtimeId?: string;
  userParticipantId: string;
}): string {
  const { baseUrl, agentMd, sessionId, agentId, runtimeId, userParticipantId } = opts;
  const agentPlaceholder = agentId ?? "<your-agent-id>";
  const identityLine =
    agentId !== undefined
      ? `\n- **Your participant id:** \`${agentId}\` (already registered — skip the \`POST /participants/register\` step).`
      : "";
  const sessionSection =
    sessionId === undefined
      ? `\n## No session selected\n\nThe user did not pin a session for you. List existing ones with \`GET ${baseUrl}/sessions\` and ask which to join, or create a new one with \`POST ${baseUrl}/sessions\` (body: \`{"slug":"…"}\`).\n`
      : `\n## Your session\n\n- **Session id:** \`${sessionId}\`\n- **Read events:** \`GET ${baseUrl}/sessions/${sessionId}/events?since=<last_seen_ts>\`\n\n### First action — say hello\n\nAfter you register as a participant, immediately POST a short prose message so the user sees you are online. Replace \`${agentPlaceholder}\` with the id returned from \`POST /participants/register\`:\n\n\`\`\`bash\ncurl -X POST '${baseUrl}/sessions/${sessionId}/events/prose' \\\n  -H "Authorization: Bearer $(cat .f-mark/.token)" \\\n  -H 'Content-Type: application/json' \\\n  -d '{"participant_id":"${agentPlaceholder}","content":"Connected. What would you like to work on?"}'\n\`\`\`\n\nThen wait for the user's next prose, read it via the \`GET /events\` endpoint above, and respond with another prose (or a \`choices\`, \`turn-end\`, etc.). End every turn with \`POST /sessions/${sessionId}/events/turn-end\`.\n`;

  return `# F-Mark agent onboarding
*Auto-generated by the running kernel at \`${baseUrl}\`. Treat this page as the authoritative live config; \`.f-mark/AGENT.md\` is a static fallback.*

## Connection

- **Base URL:** \`${baseUrl}\`
- **Bearer token:** read from \`.f-mark/.token\` in the project root. Send as \`Authorization: Bearer <token>\` on every request (the \`/health\` endpoint is the only exception).
- **WebSocket (optional):** \`${baseUrl.replace(/^http/, "ws")}/ws\` — broadcasts new event filenames in real-time.${identityLine}

## Verify your tooling

Before you send anything, check that you have the F-Mark skill installed locally so you understand the protocol fully.

### Skill (REQUIRED)
1. Check for \`.claude/skills/f-mark/SKILL.md\` in the current project.
2. If absent, copy the bundled skill from \`node_modules/f-mark/assets/claude-skill/f-mark/\` into \`.claude/skills/f-mark/\`:
   \`\`\`bash
   mkdir -p .claude/skills/f-mark
   cp -r node_modules/f-mark/assets/claude-skill/f-mark/* .claude/skills/f-mark/
   \`\`\`
3. After copying, read \`.claude/skills/f-mark/SKILL.md\` and \`.claude/skills/f-mark/api.md\` for the full reference.

${renderHooksSection(runtimeId, agentId, userParticipantId)}
${sessionSection}
---

## Composing long documents

For documents that mix prose, flow charts, and other embeds, **use
\`append_to\`** to build a single composable doc out of multiple events:

1. POST a named prose (the **anchor**). Keep new anchors **header-only**
   — leave \`content\` empty. The anchor's \`name\` is the document title.
2. Append every part with \`append_to: <anchor filename>\` on each
   subsequent POST. Pick the part's kind to match its role: prose for
   sections, flow for diagrams, file for images, html for widgets,
   choices/todo/tool-use for interactive panels.
3. The renderer collapses the anchor + all blocks into a single visible
   document, in event-arrival order.

### Common pitfalls

- Anchors are header-only. New anchors with markdown content still render
  (legacy fallback), but new authoring should keep content empty.
- Use prose \`mode: "comment"\` for comments; **never** put \`name\` on a
  comment.
- \`lines\` is comment-only and only applies to prose-text targets.
- When superseding a block, **preserve its \`append_to\`** so the slot is
  kept; otherwise the supersedor renders as a new top-level event.
- Mark removed blocks with prose \`removed: true\` (and \`supersedes:\`
  the block's filename), not empty content. A prose tombstone may
  supersede any block kind.

See \`${baseUrl}/best-practices\` for a worked four-event canonical
example, full JSON payloads, and the complete error-rule table.

---

## Full protocol (from \`.f-mark/AGENT.md\`)

${agentMd.trimStart()}
`;
}

export function registerGuideRoute(
  app: FastifyInstance,
  pOrDeps: Paths | PathDeps,
): void {
  const deps = normaliseDeps(pOrDeps);

  app.get<{ Querystring: GuideQuery }>("/guide", async (req, reply) => {
    const p = resolvePaths(deps);
    const sessionId = req.query.session_id ?? req.query.sessionId;
    const agentId = req.query.agent_id;
    const runtimeId = req.query.runtime_id;
    if (sessionId !== undefined && !(await sessionExists(p, sessionId))) {
      reply.code(404).send({ error: `session not found: ${sessionId}` });
      return;
    }
    const host = req.headers.host ?? `localhost:7777`;
    const xfProto = req.headers["x-forwarded-proto"];
    const proto =
      typeof xfProto === "string" && xfProto.length > 0 ? xfProto : "http";
    const baseUrl = `${proto}://${host}`;
    const agentMd = await readFile(p.agentMd(), "utf8");
    // Find the first registered user participant to substitute into the
    // UserPromptSubmit hook snippets. If none exists (e.g. an agent-only
    // project), fall back to the legacy `us-yourname` placeholder.
    let userParticipantId = "us-yourname";
    try {
      const parts = await listParticipants(p);
      for (const [id, part] of Object.entries(parts)) {
        if (part.kind === "user") {
          userParticipantId = id;
          break;
        }
      }
    } catch {
      // leave the fallback
    }
    reply.type("text/markdown; charset=utf-8");
    return buildGuide({
      baseUrl,
      agentMd,
      sessionId,
      agentId,
      runtimeId,
      userParticipantId,
    });
  });
}
